# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0004_auto_20160628_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadedfiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useruploadedfiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
