# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0023_auto_20160720_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=120)),
                ('parentfolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentfoldername', to='antarin.ProjectFolders')),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='projectfolders',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectfolders', to='antarin.Projects'),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='projectfolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectfoldername', to='antarin.ProjectFolders'),
        ),
    ]
