# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0024_auto_20160721_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfiles',
            name='projectfolder',
        ),
        migrations.RemoveField(
            model_name='projectfolders',
            name='foldername',
        ),
        migrations.RemoveField(
            model_name='projectfolders',
            name='parentfolder',
        ),
        migrations.AddField(
            model_name='projectfolders',
            name='folder_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectfolderreference', to='antarin.UserFolder'),
        ),
    ]
