# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0025_auto_20160721_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
