# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 21:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antarin', '0026_auto_20160721_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetailsLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=600)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectlogs', to='antarin.Projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userchanges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
