# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0029_auto_20160803_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstances',
            name='instance_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
