# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0032_auto_20160804_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstances',
            name='access_key',
            field=models.IntegerField(default=0),
        ),
    ]
