# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 16:24
from __future__ import unicode_literals

import antarin.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antarin', '0038_userinstances_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntarinFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=antarin.models.get_upload_filepath)),
            ],
        ),
        migrations.CreateModel(
            name='AntarinFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('parentfolder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_folder_reference', to='antarin.AntarinFolders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_antarin_folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AntarinProjectClouds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.IntegerField(default=0)),
                ('cloud_name', models.CharField(default='', max_length=60)),
                ('instance_id', models.CharField(default='', max_length=40)),
                ('ami_id', models.CharField(max_length=40)),
                ('region', models.CharField(default='', max_length=60)),
                ('instance_type', models.CharField(max_length=60)),
                ('security_group', models.CharField(default='launch-wizard-2', max_length=60)),
                ('dns_name', models.CharField(default='', max_length=60)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AntarinProjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_project_files', to='antarin.AntarinFiles')),
            ],
        ),
        migrations.CreateModel(
            name='AntarinProjectFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_project_folders', to='antarin.AntarinFolders')),
            ],
        ),
        migrations.CreateModel(
            name='AntarinProjectLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='AntarinProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloudFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud', to='antarin.AntarinProjectClouds')),
                ('file_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_cloud_files', to='antarin.AntarinFiles')),
            ],
        ),
        migrations.CreateModel(
            name='CloudFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_ref', to='antarin.AntarinProjectClouds')),
                ('folder_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_cloud_folders', to='antarin.AntarinFiles')),
            ],
        ),
        migrations.CreateModel(
            name='UserClouds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_user_clouds', to='antarin.AntarinProjectClouds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_clouds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_user_files', to='antarin.AntarinFiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_user_folders', to='antarin.AntarinFolders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='algofiles',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='algofiles',
            name='projectfile',
        ),
        migrations.RemoveField(
            model_name='datafiles',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='datafiles',
            name='projectfile',
        ),
        migrations.RemoveField(
            model_name='instancefolders',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='instancefolders',
            name='project_folder_ref',
        ),
        migrations.RemoveField(
            model_name='projectdetailslogger',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectdetailslogger',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectfiles',
            name='file_ref',
        ),
        migrations.RemoveField(
            model_name='projectfiles',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectfolders',
            name='folder_ref',
        ),
        migrations.RemoveField(
            model_name='projectfolders',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userinstances',
            name='keyval',
        ),
        migrations.RemoveField(
            model_name='userinstances',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userinstances',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_user_projects', to='antarin.AntarinProjects'),
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='algoFiles',
        ),
        migrations.DeleteModel(
            name='dataFiles',
        ),
        migrations.DeleteModel(
            name='InstanceFolders',
        ),
        migrations.DeleteModel(
            name='ProjectDetailsLogger',
        ),
        migrations.DeleteModel(
            name='ProjectFiles',
        ),
        migrations.DeleteModel(
            name='ProjectFolders',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='UserInstances',
        ),
        migrations.AddField(
            model_name='antarinprojectlogs',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reference', to='antarin.AntarinProjects'),
        ),
        migrations.AddField(
            model_name='antarinprojectlogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antarinprojectfolders',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ref', to='antarin.AntarinProjects'),
        ),
        migrations.AddField(
            model_name='antarinprojectfiles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='antarin.AntarinProjects'),
        ),
        migrations.AddField(
            model_name='antarinprojectclouds',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_clouds', to='antarin.AntarinProjects'),
        ),
        migrations.AddField(
            model_name='antarinfiles',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_folder_ref', to='antarin.AntarinFolders'),
        ),
        migrations.AddField(
            model_name='antarinfiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_antarin_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
