# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0039_auto_20160830_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfolders',
            name='folder_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_cloud_folders', to='antarin.AntarinFolders'),
        ),
    ]
