# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0041_auto_20160906_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antarinfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='antarin_files'),
        ),
    ]
