# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antarin', '0042_auto_20160906_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='antarinspacefiles',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_space_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antarinspacefolders',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_space_folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
