# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0043_auto_20160907_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='antarinclouds',
            name='package_active',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
