# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0044_antarinclouds_package_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antarinclouds',
            name='package_active',
            field=models.IntegerField(default=0),
        ),
    ]
