# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0046_auto_20160908_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='antarinclouds',
            name='process_running',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='antarinclouds',
            name='status',
            field=models.CharField(default='Standby', max_length=200),
        ),
    ]
