# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antarin', '0003_auto_20160627_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploadedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='user_files')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='useruploadedfiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='file',
        ),
    ]
