# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0005_auto_20160628_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data_storage_used',
            field=models.CharField(default='0 GB', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_data_storage',
            field=models.CharField(default='5 GB', max_length=20),
        ),
    ]
