# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 22:37
from __future__ import unicode_literals

import antarin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0006_auto_20160708_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadedfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=antarin.models.get_upload_filepath),
        ),
    ]
