# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antarin', '0009_auto_20160716_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfolder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userfolders', to=settings.AUTH_USER_MODEL),
        ),
    ]
