# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0027_projectdetailslogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojects',
            name='access_key',
            field=models.IntegerField(default=0),
        ),
    ]
