# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 18:39
from __future__ import unicode_literals

import antarin.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antarin', '0028_userprojects_access_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='algoFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='dataFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserInstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=40)),
                ('ami_id', models.CharField(max_length=40)),
                ('keyname', models.CharField(max_length=50)),
                ('instance_type', models.CharField(max_length=60)),
                ('security_group', models.CharField(max_length=60)),
                ('key', models.FileField(blank=True, null=True, upload_to=antarin.models.get_keypath)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectinstances', to='antarin.Projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinstances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='projectdetailslogger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projectlogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datafiles',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafiles_instanceobject', to='antarin.UserInstances'),
        ),
        migrations.AddField(
            model_name='datafiles',
            name='projectfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='antarin.ProjectFiles'),
        ),
        migrations.AddField(
            model_name='algofiles',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algofiles_instance_object', to='antarin.UserInstances'),
        ),
        migrations.AddField(
            model_name='algofiles',
            name='projectfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algo_files', to='antarin.ProjectFiles'),
        ),
    ]
