# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0030_userinstances_instance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstances',
            name='instance_id',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='userinstances',
            name='security_group',
            field=models.CharField(default='launch-wizard-2', max_length=60),
        ),
    ]
