# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 16:58
from __future__ import unicode_literals

import antarin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0031_auto_20160803_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSAKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('key_name', models.CharField(max_length=50)),
                ('key', models.FileField(blank=True, null=True, upload_to=antarin.models.get_keypath)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinstances',
            name='key',
        ),
        migrations.RemoveField(
            model_name='userinstances',
            name='keyname',
        ),
        migrations.AddField(
            model_name='userinstances',
            name='region',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='userinstances',
            name='keyval',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rsakeys', to='antarin.RSAKeys'),
        ),
    ]
