# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0033_userinstances_access_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstances',
            name='keyval',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsakeys', to='antarin.RSAKeys'),
        ),
    ]
