# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0035_auto_20160804_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstances',
            name='dns_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
