# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0036_userinstances_dns_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancefolders', to='antarin.UserInstances')),
                ('project_folder_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_folder_ref', to='antarin.ProjectFolders')),
            ],
        ),
    ]
