# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0037_instancefolders'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstances',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
