# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 00:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antarin', '0040_auto_20160901_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntarinCloudFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AntarinCloudFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='AntarinClouds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.IntegerField(default=0)),
                ('cloud_name', models.CharField(default='', max_length=60)),
                ('instance_id', models.CharField(default='', max_length=40)),
                ('ami_id', models.CharField(max_length=40)),
                ('region', models.CharField(default='', max_length=60)),
                ('instance_type', models.CharField(max_length=60)),
                ('security_group', models.CharField(default='launch-wizard-2', max_length=60)),
                ('dns_name', models.CharField(default='', max_length=60)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AntarinSpaceFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AntarinSpaceFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=60)),
                ('parentfolder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_space_folders', to='antarin.AntarinSpaceFolders')),
            ],
        ),
        migrations.CreateModel(
            name='AntarinSpaceLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='UserSpaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Admin'), ('C', 'Contributor')], max_length=1)),
                ('access_key', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='AntarinProjects',
            new_name='AntarinSpaces',
        ),
        migrations.RemoveField(
            model_name='antarinfolders',
            name='parentfolder',
        ),
        migrations.RemoveField(
            model_name='antarinfolders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='antarinprojectclouds',
            name='project',
        ),
        migrations.RemoveField(
            model_name='antarinprojectfiles',
            name='file_ref',
        ),
        migrations.RemoveField(
            model_name='antarinprojectfiles',
            name='project',
        ),
        migrations.RemoveField(
            model_name='antarinprojectfolders',
            name='folder_ref',
        ),
        migrations.RemoveField(
            model_name='antarinprojectfolders',
            name='project',
        ),
        migrations.RemoveField(
            model_name='antarinprojectlogs',
            name='project',
        ),
        migrations.RemoveField(
            model_name='antarinprojectlogs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cloudfiles',
            name='cloud',
        ),
        migrations.RemoveField(
            model_name='cloudfiles',
            name='file_ref',
        ),
        migrations.RemoveField(
            model_name='cloudfolders',
            name='cloud',
        ),
        migrations.RemoveField(
            model_name='cloudfolders',
            name='folder_ref',
        ),
        migrations.RemoveField(
            model_name='userclouds',
            name='cloud',
        ),
        migrations.RemoveField(
            model_name='userclouds',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprojects',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userprojects',
            name='user',
        ),
        migrations.RemoveField(
            model_name='antarinfiles',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='antarinfiles',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfolders',
            name='folder_ref',
        ),
        migrations.AddField(
            model_name='userfiles',
            name='parentfolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_files', to='antarin.UserFolders'),
        ),
        migrations.AddField(
            model_name='userfolders',
            name='foldername',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userfolders',
            name='parentfolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_folders', to='antarin.UserFolders'),
        ),
        migrations.AlterField(
            model_name='antarinfiles',
            name='file',
            field=models.FileField(blank=True, upload_to='antarin_files'),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='file_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_ref', to='antarin.AntarinFiles'),
        ),
        migrations.DeleteModel(
            name='AntarinFolders',
        ),
        migrations.DeleteModel(
            name='AntarinProjectClouds',
        ),
        migrations.DeleteModel(
            name='AntarinProjectFiles',
        ),
        migrations.DeleteModel(
            name='AntarinProjectFolders',
        ),
        migrations.DeleteModel(
            name='AntarinProjectLogs',
        ),
        migrations.DeleteModel(
            name='CloudFiles',
        ),
        migrations.DeleteModel(
            name='CloudFolders',
        ),
        migrations.DeleteModel(
            name='UserClouds',
        ),
        migrations.DeleteModel(
            name='UserProjects',
        ),
        migrations.AddField(
            model_name='userspaces',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_user_spaces', to='antarin.AntarinSpaces'),
        ),
        migrations.AddField(
            model_name='userspaces',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antarinspacelogs',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_reference', to='antarin.AntarinSpaces'),
        ),
        migrations.AddField(
            model_name='antarinspacelogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_space_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antarinspacefolders',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_folders', to='antarin.AntarinSpaces'),
        ),
        migrations.AddField(
            model_name='antarinspacefiles',
            name='file_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_file_reference', to='antarin.AntarinFiles'),
        ),
        migrations.AddField(
            model_name='antarinspacefiles',
            name='parentfolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_space_files', to='antarin.AntarinSpaceFolders'),
        ),
        migrations.AddField(
            model_name='antarinspacefiles',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_files', to='antarin.AntarinSpaces'),
        ),
        migrations.AddField(
            model_name='antarinclouds',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_clouds', to='antarin.AntarinSpaces'),
        ),
        migrations.AddField(
            model_name='antarinclouds',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_clouds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antarincloudfolders',
            name='cloud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_folders', to='antarin.AntarinClouds'),
        ),
        migrations.AddField(
            model_name='antarincloudfolders',
            name='parentfolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_cloud_folders', to='antarin.AntarinCloudFolders'),
        ),
        migrations.AddField(
            model_name='antarincloudfiles',
            name='cloud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_files', to='antarin.AntarinClouds'),
        ),
        migrations.AddField(
            model_name='antarincloudfiles',
            name='file_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_file_reference', to='antarin.AntarinFiles'),
        ),
        migrations.AddField(
            model_name='antarincloudfiles',
            name='parentfolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_cloud_files', to='antarin.AntarinCloudFolders'),
        ),
    ]
