# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarin', '0045_auto_20160907_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antarinclouds',
            name='package_active',
            field=models.CharField(default='', max_length=100),
        ),
    ]
